# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      OCAML: "ocaml-base-compiler.4.07.1"
      OPAM_PINS: "coq version 8.12.0"
      CPU_CORES: "1"
      DENY_WARNINGS: "1"

    container:
      image: ralfjung/opam-ci:opam2
      options: --user 1001

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: |
            _opam
          key: coq

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run CI
        run: |
          ls -al
          git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
          ci/buildjob
